---
dependency:
  name: galaxy
  options:
    ignore-certs: true

driver:
  name: docker

platforms:
  # - name: simple-lvm-storage-centos-7
  #   image: registry.centos.org/centos/systemd:latest
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   service_manager: ${MOLECULE_SERVICE_MANAGER:-systemd}
  #   capabilities:
  #     - SYS_ADMIN
  #   command: /sbin/init

  - name: centos-8-systemd
    hostname: centos
    image: mpaivabarbosa/molecule-systemd-centos:8
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    override_command: false

provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
